name: Update a pinned gist with an RSS/Atom feed
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: nanbowaner/feed-box@master
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 2d96da19937b0b18506f65764e23ba0d
      RSS_URL: 'https://zh.wikinews.org/w/index.php?title=Special:%E6%96%B0%E9%97%BB%E8%AE%A2%E9%98%85&feed=atom'
